#!/bin/zsh

# profile file. Runs on login. Environment variables are set here.

export ZDOTDIR="$HOME/.config/zsh"
export EDITOR="nvim"
export BROWSER="firefox"
[ -f "$HOME/.config/zsh/.lficons" ] && source "$HOME/.config/zsh/.lficons"
