#!/bin/zsh

# profile file. Runs on login. Environment variables are set here.

export ZDOTDIR="$HOME/.config/zsh"
export EDITOR="nvim"
export BROWSER="qutebrowser"
export FILEMANAGER="thunar"
export QT_STYLE_OVERRIDE="adwaita-dark"

[ -f "$HOME/.config/zsh/.lficons" ] && source "$HOME/.config/zsh/.lficons"
