# Enable colors, git info and change prompt.
autoload -U colors && colors
autoload -U vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' unstagedstr '%F{red}*'
zstyle ':vcs_info:git:*' stagedstr '%F{yellow}*'
zstyle ':vcs_info:git:*' formats ' %F{green}(%b%u%c%F{green})'
precmd() { vcs_info }
setopt prompt_subst
PS1='[%{$fg[cyan]%}%n%f@%{$fg[magenta]%}%M %F{8}%~${vcs_info_msg_0_}%f]$ '
setopt autocd  
stty stop undef
setopt interactive_comments
unsetopt nomatch

# History in cache directory.
HISTSIZE=2000
SAVEHIST=2000
HISTFILE=~/.cache/zsh/.history
setopt appendhistory

# Basic auto/tab complete.
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Aliases
alias sudo='sudo '
alias ls="ls --color=auto --group-directories-first"
alias vim="nvim"
alias yta="youtube-dl -x -f bestaudio/best"
alias webcam="mpv --demuxer-lavf-o=video_size=1280x720,input_format=mjpeg av://v4l2:/dev/video0 --profile=low-latency >/dev/null 2>&1 &!"

# Syntax highlighting.
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
